### PR TITLE
chg: removing UI for adding LiveChat widgets. Resolves #744

### LINKED ISSUE #744: Remove interface for adding new LiveChat widgets
Now that JS Includes are merged, we can start closing down LiveChat

### PR DESCRIPTION
**Pull request by AlanBCole**
I simply removed the form found at `admin/settings/livechat/configuration` and replaced it with a message saying:

> "Our LiveChat bundle is being replaced by our Javascript Includes module, which is a much more flexible tool for you to add various 3rd party tools to you site. Any LiveChats you have on your site will still work, but we ask you to begin replacing them and to create any new LiveChats by clicking the link below.

and providing a link to the js-include add page (`admin/content/js-includes/add/livechat`)

LiveChat widgets in use on a site at this moment should still work as I have not intentionally changed any other functionality.

### CODE REVIEW

**Review by kevincrafts — COMMENTED** [review]
What do you think of making the form disabled so someone would still have access to the license number?

**Comment by AlanBCole** [comment]
@kevincrafts That sounds like a great idea. Or perhaps simply giving the license number for someone to copy.

**Review by cathysnider — CHANGES_REQUESTED** [review]
Shouldn't we also remove the ability to enable the LiveChat bundle at admin/settings/bundles/list/available?

**Comment by cathysnider** [comment]
I agree with @kevincrafts  that the license number should still be available.

**Comment by cathysnider** [comment]
Suggested text for LiveChat Configuration Page at admin/settings/livechat/configuration:
Our LiveChat bundle is being replaced with Javascript Includes, a much more flexible tool for adding third-party solutions to your site. The LiveChats you have on your site will continue to work, but we ask you to begin replacing them and to create new LiveChats by clicking the link below.

**Comment by kevincrafts** [comment]
Looks like we should remove the behat test for this so the build tests will start passing again.

**Review by cathysnider — CHANGES_REQUESTED** [review]
- [x] If a site has not enabled the LiveChat bundle, then the bundle should not appear on the 'Available Bundles' page at admin/settings/bundles/list/available

 - [ ] If a site already had enabled LiveChat, then the bundle SHOULD appear as enabled on the 'Enabled Bundles' page at admin/settings/bundles/list

So, for sites that have enabled the bundle already, the enabled bundle should be appearing in the Enabled Bundles list. 

I believe this page is configured in https://github.com/CuBoulder/express_mono/blob/dev/modules/custom/profile_module_manager/profile_module_manager.module#L49

**Review by cathysnider — APPROVED** [review]

**Comment by kevincrafts** [comment]
Something is wrong here where this branch is causing most of the bundles not to show on the available bundles page.

Screen Shot 2020-11-30 at 1 42 51 PM
Screen Shot 2020-11-30 at 1 43 05 PM

**Comment by AlanBCole** [comment]
@kevincrafts I do not see that any bundles are not being shown. @cathysnider Do you notice any missing from the 'available' page? Also, how many are there supposed to be? Sorry if that is a silly question?

**Comment by AlanBCole** [comment]
@kevincrafts pr into this one allows us to remove the ui for enabling a bundle if the bundle_roles are removed from its .info file.
- The bundle will still be listed in the enabled tab found at `admin/settings/bundles/list` if it has already been enabled
- The bundle will no longer be listed in the available tab found at `admin/settings/bundles/list` if it is presently disabled and has the bundle_roles removed

**Review by cathysnider — APPROVED** [review]

**Review by kevincrafts — APPROVED** [review]
Approving some of my own code

**Pull request merged**
