### PR TITLE
adding nested parent/child related terms to UI for People list pages

### PR DESCRIPTION
**Pull request by AlanBCole**
I found the code in cu_article.module that accomplishes this issue's objectives for article list pages and simply copied it to the people_content_type module folder.

When a people list's edit page has options in FILTER/GROUP/ORDER -> SHOW/HIDE FILTERS set to 'SHOW' __**and**__ a corresponding terms have parent/child relationships they should show up as nested in the exposed filters in the UI.

### CODE REVIEW

**Review by kevincrafts — CHANGES_REQUESTED** [review]
I agree with Cathy that we should probably add the ability to limit what child terms appear.

**Comment by AlanBCole** [comment]
I will move issue #625 back to 'To Do' to work on it more.

**Review by cathysnider — CHANGES_REQUESTED** [review]
Good: The Department list is laid out in one column, which makes it easy to understand which tags are children. 
Good: There are now radio buttons which let you include or not include child terms. 
Bad: The "Don't Include Child Terms" radio button doesn't do anything. All the child terms are included anyway.

**Review by cathysnider — APPROVED** [review]
After discussion about what was supposed to be happening here, it looks like it is working as designed. The requested change was to the drop-down filter that site visitors use to choose the people they want to see. 

When 'include all child terms' is chosen, site visitors see this. 
Screen Shot 2020-09-24 at 1 49 58 PM


When 'include only terms selected' is chosen, site visitors see this.
Screen Shot 2020-09-24 at 1 50 32 PM

**Review by kevincrafts — APPROVED** [review]

**Pull request merged**
