### PR TITLE
Add new block for large site search form

### PR DESCRIPTION
**Pull request by kevincrafts**
This block can be placed on a page with either context, or using the layout tool with the block wrapper.

### CODE REVIEW

**Comment by cathysnider** [comment]
Questions/Comments:
1) There is now a page at url "/search" that contains a search box. Is this on purpose?
Screen Shot 2020-03-18 at 3 10 23 PM

2) Any page whose URL starts with "search" automatically has a search box on it. I'm guessing this is not on purpose. 
Screen Shot 2020-03-18 at 3 10 04 PM

**Comment by kevincrafts** [comment]
The other search blocks are the ones used on the site and are not meant to be added into other regions.

**Comment by jwfuller** [comment]
@kevincrafts Is there a way to prevent the other search boxes from being added?

**Comment by kevincrafts** [comment]
We prevent some blocks being placed by altering the form - this is a rather wide ban by preventing blocks that are provided by certain modules.  So we can prevent all blocks provided by cu_search from being placed, but not individual ones I believe. (https://github.com/CuBoulder/express_mono/blob/dev/modules/features/cu_sitewide/cu_sitewide.module#L142)

If we wanted to get around this, we could make another module to provide this block but then we would be adding in duplicate code that is being used by all the search blocks.

**Comment by jwfuller** [comment]
@kevincrafts Could you implement `hook_form_alter()` in this module as well (acting on the same form) to remove the specific search blocks that are not allowed?

**Comment by kevincrafts** [comment]
I'm not sure what to do about that, since I guess it seems context is evaluating the url that you are on, which is never going to be the custom 404 url.

I did some testing with the [Context Error module](https://www.drupal.org/project/context_error), which did make this work.

Let's discuss at the meeting next week.

**Comment by jwfuller** [comment]
@kevincrafts will test with Express Layout

**Comment by kevincrafts** [comment]
I'm not totally sure how the Navigation404 module works (https://github.com/CuBoulder/express_mono/blob/dev/modules/contrib/navigation404/navigation404.module), but it does not go through the same loading process which would trigger the layout to be loaded.

Custom 404 page (with a sidebar block placed with Layout): https://www.colorado.edu/p15a75c78bd6/my-404

404 page to test with: https://www.colorado.edu/p15a75c78bd6/fjdhfkadjhf

**Pull request merged**
