### PR TITLE
new: created block to be inserted on Person pages. Resolves #643

### LINKED ISSUE #643: Allow Faculty Publications block to inherit information on a person node
For larger departments, this could be an easy way to add this content if you could add a single block via context vs adding individual blocks.

### PR DESCRIPTION
**Pull request by AlanBCole**
1. Can be configured by visiting /admin/structure/block/manage/cu_faculty_publications_bundle/person_publications_list/configure
2. Can be inserted via Context (see issue comments #643)
3. grabs email from node of the person page it is loaded on. No other configuration/filter setup necessary
4. For logged-in users output should be basically the same as other blocks created with the cu_faculty_publications_bundle, with the following exceptions:
    - there are only a Person's 5 most recent publications listed as a default (can be changed by step 1. above)
    - the results are only related to the email found on a Person page.
5. For non-logged-in users, if a Person has no publications the block is simply not rendered

### CODE REVIEW

**Review by kevincrafts — CHANGES_REQUESTED** [review]
Rather than using the url to find the node id, then using the node load function, I think it's a bit easier to just use the menu_get_object() function.  Tests by others have also found this to be the way more performant method of getting at the same type of data.

You can start with just checking to see if you're getting the node data and making sure the node is the type you want:

if (($node = menu_get_object()) && ($node->type == 'person)) {
  // DO STUFF HERE.
}

**Review by cathysnider — APPROVED** [review]

**Comment by kevincrafts** [comment]
I wonder if we should have the same number of results/paging options as the other block?

I guess what I'm wondering, is if this gets placed on a site showing the most recent 5 publications, how would you get to a list of further publications, without the need for creating additional pages and blocks for each faculty member?

**Comment by AlanBCole** [comment]
@kevincrafts I guess at the moment the site editor or owner could configure the block to show as many results as they wish. It should still page if they ask for more than 20 results.

What does everyone think of these ideas for showing more than the small default list:
- put a select list at the bottom of the new block with which a user could select an amount of publications to list
- have the title of the block be a link to a page/content type with a larger list
- simply include more configuration options in the block's configuration form that a site editor only has access to

**Comment by cathysnider** [comment]
These are good ideas. Our clients will definitely want a little more control over the number of results shown. The linked title idea is interesting and I'd like to see how it looks.

**Comment by kevincrafts** [comment]
so one thing you could do is to set up a page at a specific path which could also have an argument that could be used to display the person's name and filter the larger list by their email, rather than setting up a bunch of unique pages for this.

Just trying to think of how to make things easier for departments that have a lot of faculty members.

**Comment by AlanBCole** [comment]
Yes. That is kind of what I was imagining, too. Do you think it is worth caching the larger lists of publications on a page like this?

**Comment by kevincrafts** [comment]
I think rather than using all these arguments in the url (siteurl/publications/Gene%20Hayworth/all?email=gene.hayworth%40Colorado.EDU&return_url=node/33), we could just pass their node number instead, though we might want a different path (siteurl/faculty-publications/33) and from there we could pull the email address and name and set the title of the page based on that rather than a generic title, and then a heading underneath. This would be better for SEO as well.

**Review by cathysnider — APPROVED** [review]
This block is looking good:

- [x] Number of publications to show can be set
- [x] A Block Designer style can be applied to block
- [x] If the block is applied to non-person pages, nothing happens (a good result)
- [x] Error messages (such as "no publications found" or "can't connect to database") are displayed as they should be
- [x] If more publications exist than are requested shown, there's a "see full list" link at bottom of block

**Comment by AlanBCole** [comment]
@kevincrafts Sounds good. I didn't like the url either but was just trying to not pull from the database again. Easy change.

**Review by cathysnider — CHANGES_REQUESTED** [review]
What I'm seeing is: The link "See a full list of {PersonName} publications" but then, there are no publications there. 

Screen Shot 2020-11-10 at 10 46 33 AM

Screen Shot 2020-11-10 at 10 46 53 AM

**Review by kevincrafts — CHANGES_REQUESTED** [review]
I would use a title callback function in the menu hook to set the title to something more SEO friendly.  Perhaps something like "Faculty Publications from: Firstname Lastname" and replace the link with something like "View webpage" in smaller text.

**Comment by AlanBCole** [comment]
@kevincrafts is there a CU class we use for smaller text, or do we have defined sizes for text?

**Comment by kevincrafts** [comment]
You can use .small-text or <small>

**Review by cathysnider — APPROVED** [review]
Publication block links to full page of publications; paginated if necessary; the page includes a link 'back to person page.'

**Comment by kevincrafts** [comment]
I would capitalize "return" here - https://github.com/CuBoulder/express_mono/blob/feature/643_1/modules/custom/cu_faculty_publications_bundle/cu_faculty_publications_bundle.module#L78

**Review by kevincrafts — APPROVED** [review]

**Pull request merged**
