### PR TITLE
Cu web components

### PR DESCRIPTION
**Pull request by brookestevens**
A custom bean called CU Web components has been created for adding Vue Apps to the page. Enable the CU Web Component Bean module. Then clear all the cache. Now you can create a new block with the block type "CU Web Component."

### CODE REVIEW

**Review by kevincrafts — COMMENTED** [review]
I would suggest that rather then using taxonomy reference fields, that these should just be list fields.  Taxonomy fields are difficult because it would require us to export and import the entire vocabulary to each site.

By using a list field, we can create a function that will provide the options. Whenever a new option is available, we can just update the function that provides them, rather than exporting and importing a taxonomy.

**Comment by brookestevens** [comment]
The branch has been updated to remove any taxonomy references.

**Review by cathysnider — CHANGES_REQUESTED** [review]
Permissions need to be added that allow developers to work on the CU Web Component bean from the browser interface. 

~~Also, all the vocabularies are gone.~~

**Comment by brookestevens** [comment]
There shouldn't be any vocabularies anymore so it's ok if they're gone. Also, I can't add the edit button in the admin UI because the bean was made as a plugin, not as a features export. I chose to make it a plugin because I needed AJAX in the form and I couldn't do it in the UI. Also, I don't think that bean plugins are compatible with the admin UI anyway. Is being able to edit from the admin UI a required feature?

**Comment by cathysnider** [comment]
@brookestevens  Is there a Resource ID I can plug in?

**Comment by cathysnider** [comment]
Resource ID: 1IF1JT4wzb38827Mklm0E2PEBnYekwN9l-Il0mChScsg

**Comment by cathysnider** [comment]
Looks really good. With proper Resource ID and proper setup, the Web Component bean is working well. 

There's only one issue at the moment: the block title is coming from the data source, when it should be coming from the Bean Title. Our customers are used to setting their own block title. 

beanTitle

pageOne

**Comment by brookestevens** [comment]
Updated to show the Bean Title in the web component. I Also edited the CSS to prevent the Bean Title from getting rendered by Drupal again. This means that if users change the Bean Title style with the Block Designer, they won't see the changes.  This is because Vue is now responsible for rendering the markup.

**Review by cathysnider — APPROVED** [review]
Approve. This is excellent functionality to add to our Web Express offering. Our trainer can explain to clients that Block Designer and Web Components don't play well together.

**Review by kevincrafts — COMMENTED** [review]
I tried testing this branch and there are no additional bean types installed.

**Comment by cathysnider** [comment]
@kevincrafts do you mean that the module should be auto-enabled, rather than user-enabled?

**Comment by brookestevens** [comment]
I added hook_secure_permissions(). The bean should now appear for anonymous users and have the proper access permissions for all the roles. I had to clear all the cache to get the permissions working first

**Comment by cathysnider** [comment]
Success: After rebuilding secure permissions, the anonymous user is able to view the COVID web components.

**Comment by kevincrafts** [comment]
Ok I got the block to work. Here's the issues I ran into:

1. The contextual links for editing the block are missing if a title isn't entered.
2. To maintain consistent styling and presention, the Ttitle should use the markup from the block template, rather than hidden and alternate markup used.
3. I'd like to see this expanded to include other embed (such as a slate form, chat service, etc) to see how the workflow and editor experience is before we merge this in.  Depending on the type of embed the fields could be very different so I'd like to see how this will be handled.
4. Accessibile alternatives to Canvas elements
5. Web Component contents can extend beyond the edges of the container: 
image
6. Requires VPN access
7. How does user know what resource ID is?
8. Issues with Block Designer seem limited to the Canvas elements. Depending on the type of embed that is being done here, users may still need/want access to Block Designer so it shouldn't be disabled for the entire bean type.

**Comment by brookestevens** [comment]
I'm stopping development on this branch right now. The covid dashboard is up in the air so I will be starting a new branch that will also be for the dashboard. I think it's better that this be seen as a one off component rather than in a library with many.

**Pull request closed without merging**
