### PR TITLE
Feature/41 alans v2

### PR DESCRIPTION
**Pull request by AlanBCole**
This pr is intended to sort out branch feature/41. It includes code for:

1. #519 
1. #520 
1. #521 
1. #522 
1. #544 

Code for some of these issues have already been merged into branch feature/41. The code in this pr includes some refactoring so that it will be easier to add feature requests regarding elastic search queries in the future.

### CODE REVIEW

**Comment by cathysnider** [comment]
https://www-dev.colorado.edu/p15fdeb67940/

**Comment by cathysnider** [comment]
## Test Results

[ ] can filter publications by email address (#519)
[ ] can filter by organization ID (#520)
[ ] can choose date range (#521)
[ ] can display user-defined number of publications (#522)
[ ] can display by date ascending or date descending (#544)

**Comment by AlanBCole** [comment]
@cathysnider Thanks for going through all this. Just to be clear, do you see something like the following image for inputting a department id or name?

faculty-pubs

Also, do you see, in the drop down for user-defined number of publications only "None, 25, 50, ALL"? I have "None, 25, 50, 100, ALL"

Finally, the link you shared (https://www-dev.colorado.edu/p15fdeb67940/kevin-crafts-publications) doesn't load. Can you describe the options/search parameters you used that led to? Thanks again.

**Comment by AlanBCole** [comment]
@jwfuller @kevincrafts @cathysnider What sort of experience do we want for users when the search parameters they enter return with no results?
- Just a simple on screen message that says "no results found" or similar?
- Something more useful that describes which search parameter(s) returned no results.
- Something that states the problematic parameter(s) but then also shows results based on search parameters that did not have problems?

I think the third one would be nice. Any kind of informing the user of 'bad' parameters would probably make use of multiple http requests. Is that a problem in anyone's eyes?

**Comment by cathysnider** [comment]
@AlanBCole 
Alan:

You need to be on the VPN to get to www-dev.colorado.edu, specifically UCB VPN-UCOMMDEV. 

I deployed the code of Commit Hash 7a134e313eac2e77fc0fb94c96a3d879fd9e918b

No, I do not see a Department Field. 

Yes, the dropdown includes 100. Sorry for leaving that out. 

Here’s a screenshot.

screenShotFacPubs

**Comment by AlanBCole** [comment]
I just started a new D7 instance and I do not have the Department field either. I am not sure why. It is in all of the code that I added. Hmm. I'll see what I can do.

**Comment by AlanBCole** [comment]
In order to get the code changes to work in the latest couple commits, you may have to run `drush fr cu_faculty_publications_bundle`

**Comment by AlanBCole** [comment]
@kevincrafts to see the default values you will need to create a new block. It doesn't seem to work on previously created blocks for some reason.

**Comment by kevincrafts** [comment]
Can we change the sort labels to:
'Oldest to Newest' and 'Newest to Oldest'?  I am suggesting these labels from sort labels I see on other applications such as Microsoft Office?

**Pull request merged**
