### PR TITLE
Remove option for having a site be non-responsive

### PR DESCRIPTION
**Pull request by AlanBCole**
I think this achieves issue #517 . Let me know. I guess the next step would be to remove code related to this setting and just make sure that express sites are responsive by definition, not default.

### CODE REVIEW

**Comment by cathysnider** [comment]
@kevincrafts @AlanBCole In addition to removing the choice, the code should also force the site to be responsive. Or should that be another ticket?

**Comment by AlanBCole** [comment]
@kevincrafts It looks like more recent code from dev was included in the last commit. I am not sure that is an issue.

**Comment by AlanBCole** [comment]
@kevincrafts `dpm()` removed.

**Comment by AlanBCole** [comment]
Ok. So the status of each theme is set to '0'. The function cu_core_update_7069() in cu_core.install checks each theme for that property to have a 'truthy' value. Since that is not the case alpha_responsive is not being changed or set in the database. In this last code I just took out that check for theme->status.

The theme settings ui has an attempted fix.

**Comment by AlanBCole** [comment]
P.S. Changing this function means that you will have to rerun the `drush updb` to see the changes to the db. You may have to change something in the db if you want to do this on an express installation on which you previously ran this command. Let me know if you want help with this.

**Comment by AlanBCole** [comment]
@kevincrafts I think the white spacing is taken care of now. I do not know why but for a few files my ide's spacing seems to have been set automatically to tabs. Sorry about that.

**Pull request merged**
