### PR TITLE
Correct extra read more link

### PR DESCRIPTION
**Pull request by jwfuller**

### CODE REVIEW

**Comment by kevincrafts** [comment]
The feature article display has never had a read more link, and while I think it's something worth considering, I don't want to increase the scope of this bug fix into a feature change.

**Comment by kevincrafts** [comment]
Showing there was not one added through the UI:
https://github.com/CuBoulder/express/blob/dev/modules/features/cu_article/cu_article.features.field_instance.inc#L1078

And not one in the template: https://github.com/CuBoulder/express/blob/dev/modules/features/cu_article/templates/node--article--feature.tpl.php (compared to https://github.com/CuBoulder/express/blob/dev/modules/features/cu_article/templates/node--article--teaser.tpl.php)
(The code for the feature template has not changed in years)

**Comment by cathysnider** [comment]
Furthering this conversation: There **IS** a 'Read More' link on Feature Article display in Web Express.  
https://www.colorado.edu/demos/cathys-sandbox/cuengineering-magazine-2009 

ReadMoreFeatureDisplay

**Comment by cathysnider** [comment]
Sites showing "Read More" on Issue - Feature Article display:
https://www.colorado.edu/music/colorado-music-magazine-2019
https://www.colorado.edu/cuengineering/content/fall-2019-issue
https://www.colorado.edu/iriss/content/news-and-events-publication
https://www.colorado.edu/cmcinow/content/fall-2019

**Pull request merged**
