### PR TITLE
Integrate with experts.colorado.edu

### PR DESCRIPTION
**Pull request by jwfuller**

### CODE REVIEW

**Comment by cathysnider** [comment]
I suggest "No publications were found for the selected author(s)."

**Review by cathysnider — COMMENTED** [review]
## Feature Review

**v1.0**

 - [X] Create a block where you can select to show publications for an Author or an Organization
 - [X] Include the ability to filter by year (range, this year, specific year)
 - [X] Collaborate with FIS and other implementors to develop a unified look and feel 
 - [ ] Degrade gracefully using the experts.colorado.edu status page
 - [ ] Develop process for delivering feedback on data to FIS (perhaps into their JIRA instance)

 
**v1.1**

 - [X] Allow for searching for multiple Authors or Organizations
 - [ ] Implement a feature to allow a block to be activated on a Person page that will provide a publications block
 - [ ] Investigate Analytics, FIS would like to be able to report on usage and impact

**Questions and Comments:**
Did we collaborate with FIS to develop a united look and feel?
We have not yet implemented the feature that allows a block to inherits Person Node info when placed on the Person Node (#643)
What does 'degrade gracefully' look like?
What is our process for delivering feedback to FIS
Have we investigated analytics in order to report to FIS?

Overall: We currently have a deliverable that works very well -- a block that pulls publications from the experts database and filters according to department, publication date rants, faculty email address, and job type.

**Comment by AlanBCole** [comment]
@cathysnider Do you think some of the unchecked items, in the v1.0 list you included above, possible to replace into v1.1? That seems to make sense to me as completing those unchecked items, like
>Implement a feature to allow a block to be activated on a Person page that will provide a publications block

would entail a fair amount of new code and (perhaps?) touching another module's code, as well (Person module).

**Comment by jwfuller** [comment]
@AlanBCole 

> Degrade gracefully using the experts.colorado.edu status page

Means that if the feed is inaccessible, we should use the cached item even if it is expired

**Comment by jwfuller** [comment]
@AlanBCole I think it is implemented https://github.com/CuBoulder/express_mono/pull/678/files#diff-f003f0f0fe69ff3b45e547e6399d1621R245-R259.

I think cleaning up as much of the Code Climate as possible is worthwhile.

**Review by kevincrafts — APPROVED** [review]

**Review by cathysnider — CHANGES_REQUESTED** [review]
This feature looks good except for the error messages. They stretch across the width of the page and obscure graphics. 
errorMessages

**Comment by AlanBCole** [comment]
@cathysnider I finally made an issue (#742) for your comment above. I believe the issue is with the person page rather than faculty publications block.

**Comment by AlanBCole** [comment]
@cathysnider @kevincrafts I changed a couple small details as suggested by code climate, one of which was a function name. When I tested the changes everything worked well but it would be great if you both could just make sure nothing has changed that would be great.

**Review by cathysnider — APPROVED** [review]

**Review by AlanBCole — APPROVED** [review]

**Review by kevincrafts — APPROVED** [review]

**Pull request merged**
