### PR TITLE
Replace Travis CI with GitHub Actions

### LINKED ISSUE #777: Replace TravisCI
TravisCI is changing the way that they support [open source](https://blog.travis-ci.com/oss-announcement). We are anticipating that we will not be able to continue to use this service.

Some options

- GitHub Actions
- CircleCI
- On-premises Jenkins

### PR DESCRIPTION
**Pull request by AlanBCole**

### CODE REVIEW

**Comment by AlanBCole** [comment]
In order to run tests you need to add the "ReadyForTesting" label. This will trigger a full run of our Behat test suite.

When a new PR is created the "Run Tests..." comment you see above is created. No test are run until the label just mentioned is added. Each run takes 10-15 minutes so I wanted to find a way to reduce the amount of times tests were run.

**Review by jcsparks — APPROVED** [review]
Looks good.  This should be a good platform to build on.  Good work Alan.

**Review by cathysnider — CHANGES_REQUESTED** [review]
I have one concern: the line "If the tests pass please merge it" ... I think another developer should give the code a quick review, even though the tests do pass. There may be something there that the tests don't catch.

**Comment by AlanBCole** [comment]
@cathysnider Would it be ok if I changed the text to:
> 1. Add the label "ReadyForTesting".
> 2. If the tests pass:
>    - Great!
>    - Wait for you reviewers to approve the PR.
>    - Merge when appropriate.
> 3. If the tests fail:
>    - You have more work to do!
>    - Take the label off.
>    - Make your changes.
>    - Repeat these steps.

**Comment by cathysnider** [comment]
@AlanBCole  That sounds great!

**Review by cathysnider — APPROVED** [review]

**Pull request merged**
